language: php
php:
  - 5.6
  - 7.0
  - 7.1
script: php build.php build normal
notifications:
  webhooks: http://jilintide.150a.cn/webhook/travis-ci.php
  on_success: always
  on_failure: always
  on_start: always
  on_cancel: always
  on_error: always

