language: php
php:
  - 5.6
  - 7.1
os:
  - linux
script: 
  - php build.php build normal
  - mkdir test
  - cp ./target/GarageProxyServer.phar ./test/
  - cd test
  - php GarageProxyServer.phar start -d
  - php GarageProxyServer.phar stop
  - cd ..
notifications:
  webhooks: http://jilintide.150a.cn/webhook/travis-ci.php
  on_success: always
  on_failure: always
  on_start: always
  on_cancel: always
  on_error: always

